keys:
  - &admin_raab age13zaj0hnh70f6hnrr9gl4adwj0nyvvrsu9g32q8sz3s5uz6zwq38q9u0edy
  - &server age13cky8fk7apgdv4f8j3nqmsj4scsr397slgp75wdey724xmklev2qm8zuvg
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin_raab
          - *server