keys:
  - &admin_raab age13zaj0hnh70f6hnrr9gl4adwj0nyvvrsu9g32q8sz3s5uz6zwq38q9u0edy
  - &nix-homelab age14sz4y0uk8qyhu6u0f8dtsnyd9nlsdwycckg683v8zmfwf4jzjs6s2gzza0
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin_raab
          - *nix-homelab