alerting:
  custom:
    url: "https://api.pushbullet.com/v2/pushes"
    method: "POST"
    headers:
      {
        "Access-Token" : "<PLACEHOLDER>",
        "Content-Type" : "application/json"
      }
    body: |
      {
        "type": "note",
        "title": "Gatus [ALERT_TRIGGERED_OR_RESOLVED]: [ENDPOINT_NAME]",
        "body": "[ALERT_DESCRIPTION] - [ENDPOINT_URL]"
      }
    default-alert:
      description: "Request Failed!"
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 3
endpoints:
  - name: AdGuard
    url: http://adguard.server.box/
    conditions:
      - "[STATUS] == 200"
      - '[BODY] == pat(*<!doctype html>*)'
    alerts:
      - type: custom
  - name: Govee Water Alarm
    url: "icmp://192.168.1.103"
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: custom
  - name: Home Assistant
    url: http://home-assistant.server.box
    conditions:
      - "[STATUS] == 200"
      - '[BODY] == pat(*<!DOCTYPE html>*)'
    alerts:
      - type: custom
  - name: Homer.box
    url: http://server.box
    conditions:
      - "[STATUS] == 200"
      - '[BODY] == pat(*<html lang="en">*)'
    alerts:
      - type: custom
  - name: Homer.tail
    url: http://server.tail
    conditions:
      - "[STATUS] == 200"
      - '[BODY] == pat(*<html lang="en">*)'
    alerts:
      - type: custom
  - name: Jellyfin
    url: http://jellyfin.server.box/health
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
  - name: Jellyseerr
    url: http://jellyseerr.server.box/health
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
  - name: NetData
    url: http://netdata.server.box
    conditions:
      - "[STATUS] == 200"
      - '[BODY] == pat(*<!doctype html>*)'
    alerts:
      - type: custom
  - name: PFSense
    url: "https://192.168.1.1/index.php"
    client:
      insecure: true
    conditions:
      - "[CONNECTED] == true"
      - '[BODY] == pat(*<!DOCTYPE html>*)'
    alerts:
      - type: custom
  - name: Prowlarr
    url: http://prowlarr.server.box/health
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
  - name: Radarr
    url: http://radarr.server.box/health
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
  - name: Sonarr
    url: http://sonarr.server.box/health
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
  - name: Ring Doorbell
    url: "icmp://192.168.1.108"
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: custom
  - name: TP-Link Archer
    url: "icmp://192.168.1.102"
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: custom
  - name: VueTorrent
    url: "icmp://vuetorrent.server.box"
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: custom