actions:
  - title: Reboot
    icon: '<img src = "https://www.olivetin.app/resources/images/logo.png" width = "48px"/>'
    shell: sudo reboot now
  - title: Upgrade
    icon: '<img src = "https://www.olivetin.app/resources/images/logo.png" width = "48px"/>'
    shell: sudo systemctl restart podman-gatus.service