actions:
  - title: Reboot Server
    icon: '<img src = "customIcons/reboot.png" width = "48px"/>'
    shell: sudo /nix/persist/olivetin/scripts/commands.sh -r
  - title: Restart Jellyfin
    icon: '<img src = "customIcons/jellyfin.png" width = "48px"/>'
    shell: sudo /nix/persist/olivetin/scripts/commands.sh -p jellyfin
    timeout: 20
  - title: Restart Gatus
    icon: '<img src = "customIcons/gatus.png" width = "48px"/>'
    shell: sudo /nix/persist/olivetin/scripts/commands.sh -p gatus
    timeout: 20
  - title: Restart AdGuard
    icon: '<img src = "customIcons/adguard.png" width = "48px"/>'
    shell: sudo /nix/persist/olivetin/scripts/commands.sh -s adguardhome
    timeout: 20