actions:
  - title: Reboot Server
    icon: '<img src = "customIcons/reboot.png" width = "48px"/>'
    shell: sudo /nix/persist/olivetin/scripts/commands.sh reboot
  - title: Restart Jellyfin
    icon: '<img src = "customIcons/reboot.png" width = "48px"/>'
    shell: sudo /nix/persist/olivetin/scripts/commands.sh jellyfin_reboot